name: Test

on:
  schedule:
    - cron: 15 12-15,22-23 * * *
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - id: get-project
        name: Get project name
        run: echo "::set-output name=PROJECT::$(cat ken)"
      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project
      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
          ./gradlew assemblerelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-ken-apk
          path: ./**/*.apk
